language: node_js
node_js:
  - "10"

cache: yarn

jobs:
  include:
    - stage: test
      script:
        - yarn test --coverage --coverageReporters=text-lcov | coveralls
        - yarn build && bundlewatch --max-size 20kb ./dist/!(*.map)
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
