language: node_js
cache: yarn
jobs:
  include:
    - stage: test
      node_js: lts/*
      script:
        - yarn test --coverage --coverageReporters=text-lcov | coveralls
        - yarn build && bundlewatch --max-size 20kb ./dist/!(*.map)
    - stage: release
      node_js: lts/*
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - yarn build
          - npx semantic-release
