<template>
  <div id="app">
    <v-select v-model="selected" v-bind="config">
      <template v-slot:option-header="slotProps">
        <div v-if="slotProps.index > 0" class="divider"></div>
        <h2>{{ slotProps.option.text }}</h2>
      </template>
    </v-select>
    <v-select v-model="selected_two" v-bind="config_two">
      <!-- <template v-slot:option-header="slotProps">
        <div v-if="slotProps.index > 0" class="divider"></div>
        <h2>{{slotProps.option.name}}</h2>
      </template> -->
    </v-select>
  </div>
</template>

<script>
import vSelect from '../src/components/Select'
import countries from '../docs/.vuepress/data/countryCodes'
import books from '../docs/.vuepress/data/books'

export default {
  components: { vSelect },
  data: () => ({
    selected: null,
    selected_two: null,
    config_two: {
      label: 'name',
      groupBy: item => {
        
        if (
          item &&
          item.hasOwnProperty('folder_id') &&
          item.folder_id
        ) {
          const folders = [{ id: 1, name: 'Test Folder' }]
          const folder = folders.find(f => f.id == item.folder_id)
          if (folder) {
            return folder.name
          }
        }

        return undefined
      },
      options: [
    {
        "_id": "873216a50352",
        "version": 1673644662246,
        "sections": [
            {
                "type": "purpose",
                "criteria": [
                    {
                        "text": "Odio ad officia a beatae ipsum fugiat quaerat molestiae voluptatem cumque."
                    },
                    {
                        "text": "Dolore quae odit suscipit fuga."
                    }
                ],
                "name": "Inventore sint amet est inventore officiis dolorem mollitia cum amet neque et."
            },
            {
                "type": "questions",
                "criteria": [
                    {
                        "text": "Voluptatem accusamus quisquam nam vel dolorem quia aut doloribus est ullam."
                    },
                    {
                        "text": "Molestiae ut incidunt dolorem officiis enim velit iste."
                    }
                ],
                "name": "Qui facilis sint aut perferendis nostrum neque molestiae vitae corporis corrupti."
            }
        ],
        "name": "The only guide",
        "attachments": [],
        "company_id": "e2cfd1f7e3fb",
        "acting_user": {
            "_id": "817de8bdbb65",
            "name": "Larry Faudree",
            "username": "larry",
            "email_address": "larry@breezyhr.com",
            "type": null,
            "profile_photo_url": "https://avatar-cdn.breezy.hr/139af/16337536355.png",
            "initial": "L",
            "hex_color": "color3",
            "tz_offset": "240",
            "google_mail": true,
            "outlook_mail": null
        },
        "folder_id": "",
        "$$hashKey": "object:2576"
    },
    {
        "name": "None",
        "$$hashKey": "object:2577"
    }
],
    },
    config: {
      // options: countries,
      label: 'text',
      groupBy: 'type',
      options: [
        {
          $$hashKey: 'object:3143',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/New_York',
          offset: 300,
          text: 'GMT-05:00 - America/New_York',
          type: 'Recent',
        },
        {
          $$hashKey: 'object:3145',
          abbr: 'GMT',
          gmt: '+00:00',
          name: 'Africa/Abidjan',
          offset: 0,
          text: 'GMT+00:00 - Africa/Abidjan',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3146',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Africa/Algiers',
          offset: -60,
          text: 'GMT+01:00 - Africa/Algiers',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3147',
          abbr: 'GMT',
          gmt: '+00:00',
          name: 'Africa/Bissau',
          offset: 0,
          text: 'GMT+00:00 - Africa/Bissau',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3148',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Africa/Cairo',
          offset: -120,
          text: 'GMT+02:00 - Africa/Cairo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3149',
          abbr: '+01',
          gmt: '+01:00',
          name: 'Africa/Casablanca',
          offset: -60,
          text: 'GMT+01:00 - Africa/Casablanca',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3150',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Africa/Ceuta',
          offset: -60,
          text: 'GMT+01:00 - Africa/Ceuta',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3151',
          abbr: '+01',
          gmt: '+01:00',
          name: 'Africa/El_Aaiun',
          offset: -60,
          text: 'GMT+01:00 - Africa/El_Aaiun',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3152',
          abbr: 'SAST',
          gmt: '+02:00',
          name: 'Africa/Johannesburg',
          offset: -120,
          text: 'GMT+02:00 - Africa/Johannesburg',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3153',
          abbr: 'CAT',
          gmt: '+02:00',
          name: 'Africa/Juba',
          offset: -120,
          text: 'GMT+02:00 - Africa/Juba',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3154',
          abbr: 'CAT',
          gmt: '+02:00',
          name: 'Africa/Khartoum',
          offset: -120,
          text: 'GMT+02:00 - Africa/Khartoum',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3155',
          abbr: 'WAT',
          gmt: '+01:00',
          name: 'Africa/Lagos',
          offset: -60,
          text: 'GMT+01:00 - Africa/Lagos',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3156',
          abbr: 'CAT',
          gmt: '+02:00',
          name: 'Africa/Maputo',
          offset: -120,
          text: 'GMT+02:00 - Africa/Maputo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3157',
          abbr: 'GMT',
          gmt: '+00:00',
          name: 'Africa/Monrovia',
          offset: 0,
          text: 'GMT+00:00 - Africa/Monrovia',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3158',
          abbr: 'EAT',
          gmt: '+03:00',
          name: 'Africa/Nairobi',
          offset: -180,
          text: 'GMT+03:00 - Africa/Nairobi',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3159',
          abbr: 'WAT',
          gmt: '+01:00',
          name: 'Africa/Ndjamena',
          offset: -60,
          text: 'GMT+01:00 - Africa/Ndjamena',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3160',
          abbr: 'GMT',
          gmt: '+00:00',
          name: 'Africa/Sao_Tome',
          offset: 0,
          text: 'GMT+00:00 - Africa/Sao_Tome',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3161',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Africa/Tripoli',
          offset: -120,
          text: 'GMT+02:00 - Africa/Tripoli',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3162',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Africa/Tunis',
          offset: -60,
          text: 'GMT+01:00 - Africa/Tunis',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3163',
          abbr: 'CAT',
          gmt: '+02:00',
          name: 'Africa/Windhoek',
          offset: -120,
          text: 'GMT+02:00 - Africa/Windhoek',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3164',
          abbr: 'HST',
          gmt: '-10:00',
          name: 'America/Adak',
          offset: 600,
          text: 'GMT-10:00 - America/Adak',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3165',
          abbr: 'AKST',
          gmt: '-09:00',
          name: 'America/Anchorage',
          offset: 540,
          text: 'GMT-09:00 - America/Anchorage',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3166',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Araguaina',
          offset: 180,
          text: 'GMT-03:00 - America/Araguaina',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3167',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/Buenos_Aires',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/Buenos_Aires',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3168',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/Catamarca',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/Catamarca',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3169',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/Cordoba',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/Cordoba',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3170',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/Jujuy',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/Jujuy',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3171',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/La_Rioja',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/La_Rioja',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3172',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/Mendoza',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/Mendoza',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3173',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/Rio_Gallegos',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/Rio_Gallegos',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3174',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/Salta',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/Salta',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3175',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/San_Juan',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/San_Juan',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3176',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/San_Luis',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/San_Luis',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3177',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/Tucuman',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/Tucuman',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3178',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Argentina/Ushuaia',
          offset: 180,
          text: 'GMT-03:00 - America/Argentina/Ushuaia',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3179',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Asuncion',
          offset: 180,
          text: 'GMT-03:00 - America/Asuncion',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3180',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Bahia',
          offset: 180,
          text: 'GMT-03:00 - America/Bahia',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3181',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Bahia_Banderas',
          offset: 360,
          text: 'GMT-06:00 - America/Bahia_Banderas',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3182',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'America/Barbados',
          offset: 240,
          text: 'GMT-04:00 - America/Barbados',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3183',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Belem',
          offset: 180,
          text: 'GMT-03:00 - America/Belem',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3184',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Belize',
          offset: 360,
          text: 'GMT-06:00 - America/Belize',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3185',
          abbr: '-04',
          gmt: '-04:00',
          name: 'America/Boa_Vista',
          offset: 240,
          text: 'GMT-04:00 - America/Boa_Vista',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3186',
          abbr: '-05',
          gmt: '-05:00',
          name: 'America/Bogota',
          offset: 300,
          text: 'GMT-05:00 - America/Bogota',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3187',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Boise',
          offset: 420,
          text: 'GMT-07:00 - America/Boise',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3188',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Cambridge_Bay',
          offset: 420,
          text: 'GMT-07:00 - America/Cambridge_Bay',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3189',
          abbr: '-04',
          gmt: '-04:00',
          name: 'America/Campo_Grande',
          offset: 240,
          text: 'GMT-04:00 - America/Campo_Grande',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3190',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Cancun',
          offset: 300,
          text: 'GMT-05:00 - America/Cancun',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3191',
          abbr: '-04',
          gmt: '-04:00',
          name: 'America/Caracas',
          offset: 240,
          text: 'GMT-04:00 - America/Caracas',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3192',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Cayenne',
          offset: 180,
          text: 'GMT-03:00 - America/Cayenne',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3193',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Chicago',
          offset: 360,
          text: 'GMT-06:00 - America/Chicago',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3194',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Chihuahua',
          offset: 420,
          text: 'GMT-07:00 - America/Chihuahua',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3195',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Costa_Rica',
          offset: 360,
          text: 'GMT-06:00 - America/Costa_Rica',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3196',
          abbr: '-04',
          gmt: '-04:00',
          name: 'America/Cuiaba',
          offset: 240,
          text: 'GMT-04:00 - America/Cuiaba',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3197',
          abbr: 'GMT',
          gmt: '+00:00',
          name: 'America/Danmarkshavn',
          offset: 0,
          text: 'GMT+00:00 - America/Danmarkshavn',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3198',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Dawson',
          offset: 420,
          text: 'GMT-07:00 - America/Dawson',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3199',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Dawson_Creek',
          offset: 420,
          text: 'GMT-07:00 - America/Dawson_Creek',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3200',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Denver',
          offset: 420,
          text: 'GMT-07:00 - America/Denver',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3201',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Detroit',
          offset: 300,
          text: 'GMT-05:00 - America/Detroit',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3202',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Edmonton',
          offset: 420,
          text: 'GMT-07:00 - America/Edmonton',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3203',
          abbr: '-05',
          gmt: '-05:00',
          name: 'America/Eirunepe',
          offset: 300,
          text: 'GMT-05:00 - America/Eirunepe',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3204',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/El_Salvador',
          offset: 360,
          text: 'GMT-06:00 - America/El_Salvador',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3205',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Fort_Nelson',
          offset: 420,
          text: 'GMT-07:00 - America/Fort_Nelson',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3206',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Fort_Wayne',
          offset: 300,
          text: 'GMT-05:00 - America/Fort_Wayne',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3207',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Fortaleza',
          offset: 180,
          text: 'GMT-03:00 - America/Fortaleza',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3208',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'America/Glace_Bay',
          offset: 240,
          text: 'GMT-04:00 - America/Glace_Bay',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3209',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Godthab',
          offset: 180,
          text: 'GMT-03:00 - America/Godthab',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3210',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'America/Goose_Bay',
          offset: 240,
          text: 'GMT-04:00 - America/Goose_Bay',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3211',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Grand_Turk',
          offset: 300,
          text: 'GMT-05:00 - America/Grand_Turk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3212',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Guatemala',
          offset: 360,
          text: 'GMT-06:00 - America/Guatemala',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3213',
          abbr: '-05',
          gmt: '-05:00',
          name: 'America/Guayaquil',
          offset: 300,
          text: 'GMT-05:00 - America/Guayaquil',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3214',
          abbr: '-04',
          gmt: '-04:00',
          name: 'America/Guyana',
          offset: 240,
          text: 'GMT-04:00 - America/Guyana',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3215',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'America/Halifax',
          offset: 240,
          text: 'GMT-04:00 - America/Halifax',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3216',
          abbr: 'CST',
          gmt: '-05:00',
          name: 'America/Havana',
          offset: 300,
          text: 'GMT-05:00 - America/Havana',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3217',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Hermosillo',
          offset: 420,
          text: 'GMT-07:00 - America/Hermosillo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3218',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Indiana/Knox',
          offset: 360,
          text: 'GMT-06:00 - America/Indiana/Knox',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3219',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Indiana/Marengo',
          offset: 300,
          text: 'GMT-05:00 - America/Indiana/Marengo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3220',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Indiana/Petersburg',
          offset: 300,
          text: 'GMT-05:00 - America/Indiana/Petersburg',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3221',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Indiana/Tell_City',
          offset: 360,
          text: 'GMT-06:00 - America/Indiana/Tell_City',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3222',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Indiana/Vevay',
          offset: 300,
          text: 'GMT-05:00 - America/Indiana/Vevay',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3223',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Indiana/Vincennes',
          offset: 300,
          text: 'GMT-05:00 - America/Indiana/Vincennes',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3224',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Indiana/Winamac',
          offset: 300,
          text: 'GMT-05:00 - America/Indiana/Winamac',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3225',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Inuvik',
          offset: 420,
          text: 'GMT-07:00 - America/Inuvik',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3226',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Iqaluit',
          offset: 300,
          text: 'GMT-05:00 - America/Iqaluit',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3227',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Jamaica',
          offset: 300,
          text: 'GMT-05:00 - America/Jamaica',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3228',
          abbr: 'AKST',
          gmt: '-09:00',
          name: 'America/Juneau',
          offset: 540,
          text: 'GMT-09:00 - America/Juneau',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3229',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Kentucky/Louisville',
          offset: 300,
          text: 'GMT-05:00 - America/Kentucky/Louisville',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3230',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Kentucky/Monticello',
          offset: 300,
          text: 'GMT-05:00 - America/Kentucky/Monticello',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3231',
          abbr: '-04',
          gmt: '-04:00',
          name: 'America/La_Paz',
          offset: 240,
          text: 'GMT-04:00 - America/La_Paz',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3232',
          abbr: '-05',
          gmt: '-05:00',
          name: 'America/Lima',
          offset: 300,
          text: 'GMT-05:00 - America/Lima',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3233',
          abbr: 'PST',
          gmt: '-08:00',
          name: 'America/Los_Angeles',
          offset: 480,
          text: 'GMT-08:00 - America/Los_Angeles',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3234',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Maceio',
          offset: 180,
          text: 'GMT-03:00 - America/Maceio',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3235',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Managua',
          offset: 360,
          text: 'GMT-06:00 - America/Managua',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3236',
          abbr: '-04',
          gmt: '-04:00',
          name: 'America/Manaus',
          offset: 240,
          text: 'GMT-04:00 - America/Manaus',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3237',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'America/Martinique',
          offset: 240,
          text: 'GMT-04:00 - America/Martinique',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3238',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Matamoros',
          offset: 360,
          text: 'GMT-06:00 - America/Matamoros',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3239',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Mazatlan',
          offset: 420,
          text: 'GMT-07:00 - America/Mazatlan',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3240',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Menominee',
          offset: 360,
          text: 'GMT-06:00 - America/Menominee',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3241',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Merida',
          offset: 360,
          text: 'GMT-06:00 - America/Merida',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3242',
          abbr: 'AKST',
          gmt: '-09:00',
          name: 'America/Metlakatla',
          offset: 540,
          text: 'GMT-09:00 - America/Metlakatla',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3243',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Mexico_City',
          offset: 360,
          text: 'GMT-06:00 - America/Mexico_City',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3244',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Miquelon',
          offset: 180,
          text: 'GMT-03:00 - America/Miquelon',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3245',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'America/Moncton',
          offset: 240,
          text: 'GMT-04:00 - America/Moncton',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3246',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Monterrey',
          offset: 360,
          text: 'GMT-06:00 - America/Monterrey',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3247',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Montevideo',
          offset: 180,
          text: 'GMT-03:00 - America/Montevideo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3248',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/New_York',
          offset: 300,
          text: 'GMT-05:00 - America/New_York',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3249',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Nipigon',
          offset: 300,
          text: 'GMT-05:00 - America/Nipigon',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3250',
          abbr: 'AKST',
          gmt: '-09:00',
          name: 'America/Nome',
          offset: 540,
          text: 'GMT-09:00 - America/Nome',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3251',
          abbr: '-02',
          gmt: '-02:00',
          name: 'America/Noronha',
          offset: 120,
          text: 'GMT-02:00 - America/Noronha',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3252',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/North_Dakota/Beulah',
          offset: 360,
          text: 'GMT-06:00 - America/North_Dakota/Beulah',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3253',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/North_Dakota/Center',
          offset: 360,
          text: 'GMT-06:00 - America/North_Dakota/Center',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3254',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/North_Dakota/New_Salem',
          offset: 360,
          text: 'GMT-06:00 - America/North_Dakota/New_Salem',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3255',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Ojinaga',
          offset: 420,
          text: 'GMT-07:00 - America/Ojinaga',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3256',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Panama',
          offset: 300,
          text: 'GMT-05:00 - America/Panama',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3257',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Pangnirtung',
          offset: 300,
          text: 'GMT-05:00 - America/Pangnirtung',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3258',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Paramaribo',
          offset: 180,
          text: 'GMT-03:00 - America/Paramaribo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3259',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Phoenix',
          offset: 420,
          text: 'GMT-07:00 - America/Phoenix',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3260',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Port-au-Prince',
          offset: 300,
          text: 'GMT-05:00 - America/Port-au-Prince',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3261',
          abbr: '-04',
          gmt: '-04:00',
          name: 'America/Porto_Velho',
          offset: 240,
          text: 'GMT-04:00 - America/Porto_Velho',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3262',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'America/Puerto_Rico',
          offset: 240,
          text: 'GMT-04:00 - America/Puerto_Rico',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3263',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Punta_Arenas',
          offset: 180,
          text: 'GMT-03:00 - America/Punta_Arenas',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3264',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Rainy_River',
          offset: 360,
          text: 'GMT-06:00 - America/Rainy_River',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3265',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Rankin_Inlet',
          offset: 360,
          text: 'GMT-06:00 - America/Rankin_Inlet',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3266',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Recife',
          offset: 180,
          text: 'GMT-03:00 - America/Recife',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3267',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Regina',
          offset: 360,
          text: 'GMT-06:00 - America/Regina',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3268',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Resolute',
          offset: 360,
          text: 'GMT-06:00 - America/Resolute',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3269',
          abbr: '-05',
          gmt: '-05:00',
          name: 'America/Rio_Branco',
          offset: 300,
          text: 'GMT-05:00 - America/Rio_Branco',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3270',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Santarem',
          offset: 180,
          text: 'GMT-03:00 - America/Santarem',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3271',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Santiago',
          offset: 180,
          text: 'GMT-03:00 - America/Santiago',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3272',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'America/Santo_Domingo',
          offset: 240,
          text: 'GMT-04:00 - America/Santo_Domingo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3273',
          abbr: '-03',
          gmt: '-03:00',
          name: 'America/Sao_Paulo',
          offset: 180,
          text: 'GMT-03:00 - America/Sao_Paulo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3274',
          abbr: '-01',
          gmt: '-01:00',
          name: 'America/Scoresbysund',
          offset: 60,
          text: 'GMT-01:00 - America/Scoresbysund',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3275',
          abbr: 'AKST',
          gmt: '-09:00',
          name: 'America/Sitka',
          offset: 540,
          text: 'GMT-09:00 - America/Sitka',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3276',
          abbr: 'NST',
          gmt: '-03:30',
          name: 'America/St_Johns',
          offset: 210,
          text: 'GMT-03:30 - America/St_Johns',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3277',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Swift_Current',
          offset: 360,
          text: 'GMT-06:00 - America/Swift_Current',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3278',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Tegucigalpa',
          offset: 360,
          text: 'GMT-06:00 - America/Tegucigalpa',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3279',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'America/Thule',
          offset: 240,
          text: 'GMT-04:00 - America/Thule',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3280',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Thunder_Bay',
          offset: 300,
          text: 'GMT-05:00 - America/Thunder_Bay',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3281',
          abbr: 'PST',
          gmt: '-08:00',
          name: 'America/Tijuana',
          offset: 480,
          text: 'GMT-08:00 - America/Tijuana',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3282',
          abbr: 'EST',
          gmt: '-05:00',
          name: 'America/Toronto',
          offset: 300,
          text: 'GMT-05:00 - America/Toronto',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3283',
          abbr: 'PST',
          gmt: '-08:00',
          name: 'America/Vancouver',
          offset: 480,
          text: 'GMT-08:00 - America/Vancouver',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3284',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Whitehorse',
          offset: 420,
          text: 'GMT-07:00 - America/Whitehorse',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3285',
          abbr: 'CST',
          gmt: '-06:00',
          name: 'America/Winnipeg',
          offset: 360,
          text: 'GMT-06:00 - America/Winnipeg',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3286',
          abbr: 'AKST',
          gmt: '-09:00',
          name: 'America/Yakutat',
          offset: 540,
          text: 'GMT-09:00 - America/Yakutat',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3287',
          abbr: 'MST',
          gmt: '-07:00',
          name: 'America/Yellowknife',
          offset: 420,
          text: 'GMT-07:00 - America/Yellowknife',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3288',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Antarctica/Casey',
          offset: -660,
          text: 'GMT+11:00 - Antarctica/Casey',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3289',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Antarctica/Davis',
          offset: -420,
          text: 'GMT+07:00 - Antarctica/Davis',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3290',
          abbr: 'AEDT',
          gmt: '+11:00',
          name: 'Antarctica/Macquarie',
          offset: -660,
          text: 'GMT+11:00 - Antarctica/Macquarie',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3291',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Antarctica/Mawson',
          offset: -300,
          text: 'GMT+05:00 - Antarctica/Mawson',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3292',
          abbr: '-03',
          gmt: '-03:00',
          name: 'Antarctica/Palmer',
          offset: 180,
          text: 'GMT-03:00 - Antarctica/Palmer',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3293',
          abbr: '-03',
          gmt: '-03:00',
          name: 'Antarctica/Rothera',
          offset: 180,
          text: 'GMT-03:00 - Antarctica/Rothera',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3294',
          abbr: '+00',
          gmt: '+00:00',
          name: 'Antarctica/Troll',
          offset: 0,
          text: 'GMT+00:00 - Antarctica/Troll',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3295',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Antarctica/Vostok',
          offset: -360,
          text: 'GMT+06:00 - Antarctica/Vostok',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3296',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Asia/Almaty',
          offset: -360,
          text: 'GMT+06:00 - Asia/Almaty',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3297',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Asia/Amman',
          offset: -120,
          text: 'GMT+02:00 - Asia/Amman',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3298',
          abbr: '+12',
          gmt: '+12:00',
          name: 'Asia/Anadyr',
          offset: -720,
          text: 'GMT+12:00 - Asia/Anadyr',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3299',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Aqtau',
          offset: -300,
          text: 'GMT+05:00 - Asia/Aqtau',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3300',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Aqtobe',
          offset: -300,
          text: 'GMT+05:00 - Asia/Aqtobe',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3301',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Ashgabat',
          offset: -300,
          text: 'GMT+05:00 - Asia/Ashgabat',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3302',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Atyrau',
          offset: -300,
          text: 'GMT+05:00 - Asia/Atyrau',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3303',
          abbr: '+03',
          gmt: '+03:00',
          name: 'Asia/Baghdad',
          offset: -180,
          text: 'GMT+03:00 - Asia/Baghdad',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3304',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Asia/Baku',
          offset: -240,
          text: 'GMT+04:00 - Asia/Baku',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3305',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Asia/Bangkok',
          offset: -420,
          text: 'GMT+07:00 - Asia/Bangkok',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3306',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Asia/Barnaul',
          offset: -420,
          text: 'GMT+07:00 - Asia/Barnaul',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3307',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Asia/Beirut',
          offset: -120,
          text: 'GMT+02:00 - Asia/Beirut',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3308',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Asia/Bishkek',
          offset: -360,
          text: 'GMT+06:00 - Asia/Bishkek',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3309',
          abbr: '+08',
          gmt: '+08:00',
          name: 'Asia/Brunei',
          offset: -480,
          text: 'GMT+08:00 - Asia/Brunei',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3310',
          abbr: '+09',
          gmt: '+09:00',
          name: 'Asia/Chita',
          offset: -540,
          text: 'GMT+09:00 - Asia/Chita',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3311',
          abbr: '+08',
          gmt: '+08:00',
          name: 'Asia/Choibalsan',
          offset: -480,
          text: 'GMT+08:00 - Asia/Choibalsan',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3312',
          abbr: '+0530',
          gmt: '+05:30',
          name: 'Asia/Colombo',
          offset: -330,
          text: 'GMT+05:30 - Asia/Colombo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3313',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Asia/Damascus',
          offset: -120,
          text: 'GMT+02:00 - Asia/Damascus',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3314',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Asia/Dhaka',
          offset: -360,
          text: 'GMT+06:00 - Asia/Dhaka',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3315',
          abbr: '+09',
          gmt: '+09:00',
          name: 'Asia/Dili',
          offset: -540,
          text: 'GMT+09:00 - Asia/Dili',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3316',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Asia/Dubai',
          offset: -240,
          text: 'GMT+04:00 - Asia/Dubai',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3317',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Dushanbe',
          offset: -300,
          text: 'GMT+05:00 - Asia/Dushanbe',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3318',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Asia/Famagusta',
          offset: -120,
          text: 'GMT+02:00 - Asia/Famagusta',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3319',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Asia/Gaza',
          offset: -120,
          text: 'GMT+02:00 - Asia/Gaza',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3320',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Asia/Hebron',
          offset: -120,
          text: 'GMT+02:00 - Asia/Hebron',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3321',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Asia/Ho_Chi_Minh',
          offset: -420,
          text: 'GMT+07:00 - Asia/Ho_Chi_Minh',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3322',
          abbr: 'HKT',
          gmt: '+08:00',
          name: 'Asia/Hong_Kong',
          offset: -480,
          text: 'GMT+08:00 - Asia/Hong_Kong',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3323',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Asia/Hovd',
          offset: -420,
          text: 'GMT+07:00 - Asia/Hovd',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3324',
          abbr: '+08',
          gmt: '+08:00',
          name: 'Asia/Irkutsk',
          offset: -480,
          text: 'GMT+08:00 - Asia/Irkutsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3325',
          abbr: 'WIB',
          gmt: '+07:00',
          name: 'Asia/Jakarta',
          offset: -420,
          text: 'GMT+07:00 - Asia/Jakarta',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3326',
          abbr: 'WIT',
          gmt: '+09:00',
          name: 'Asia/Jayapura',
          offset: -540,
          text: 'GMT+09:00 - Asia/Jayapura',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3327',
          abbr: 'IST',
          gmt: '+02:00',
          name: 'Asia/Jerusalem',
          offset: -120,
          text: 'GMT+02:00 - Asia/Jerusalem',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3328',
          abbr: '+0430',
          gmt: '+04:30',
          name: 'Asia/Kabul',
          offset: -270,
          text: 'GMT+04:30 - Asia/Kabul',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3329',
          abbr: '+12',
          gmt: '+12:00',
          name: 'Asia/Kamchatka',
          offset: -720,
          text: 'GMT+12:00 - Asia/Kamchatka',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3330',
          abbr: 'PKT',
          gmt: '+05:00',
          name: 'Asia/Karachi',
          offset: -300,
          text: 'GMT+05:00 - Asia/Karachi',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3331',
          abbr: '+0545',
          gmt: '+05:45',
          name: 'Asia/Kathmandu',
          offset: -345,
          text: 'GMT+05:45 - Asia/Kathmandu',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3332',
          abbr: '+09',
          gmt: '+09:00',
          name: 'Asia/Khandyga',
          offset: -540,
          text: 'GMT+09:00 - Asia/Khandyga',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3333',
          abbr: 'IST',
          gmt: '+05:30',
          name: 'Asia/Kolkata',
          offset: -330,
          text: 'GMT+05:30 - Asia/Kolkata',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3334',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Asia/Krasnoyarsk',
          offset: -420,
          text: 'GMT+07:00 - Asia/Krasnoyarsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3335',
          abbr: '+08',
          gmt: '+08:00',
          name: 'Asia/Kuala_Lumpur',
          offset: -480,
          text: 'GMT+08:00 - Asia/Kuala_Lumpur',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3336',
          abbr: '+08',
          gmt: '+08:00',
          name: 'Asia/Kuching',
          offset: -480,
          text: 'GMT+08:00 - Asia/Kuching',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3337',
          abbr: 'CST',
          gmt: '+08:00',
          name: 'Asia/Macau',
          offset: -480,
          text: 'GMT+08:00 - Asia/Macau',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3338',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Asia/Magadan',
          offset: -660,
          text: 'GMT+11:00 - Asia/Magadan',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3339',
          abbr: 'WITA',
          gmt: '+08:00',
          name: 'Asia/Makassar',
          offset: -480,
          text: 'GMT+08:00 - Asia/Makassar',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3340',
          abbr: 'PHT',
          gmt: '+08:00',
          name: 'Asia/Manila',
          offset: -480,
          text: 'GMT+08:00 - Asia/Manila',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3341',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Asia/Nicosia',
          offset: -120,
          text: 'GMT+02:00 - Asia/Nicosia',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3342',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Asia/Novokuznetsk',
          offset: -420,
          text: 'GMT+07:00 - Asia/Novokuznetsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3343',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Asia/Novosibirsk',
          offset: -420,
          text: 'GMT+07:00 - Asia/Novosibirsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3344',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Asia/Omsk',
          offset: -360,
          text: 'GMT+06:00 - Asia/Omsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3345',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Oral',
          offset: -300,
          text: 'GMT+05:00 - Asia/Oral',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3346',
          abbr: 'WIB',
          gmt: '+07:00',
          name: 'Asia/Pontianak',
          offset: -420,
          text: 'GMT+07:00 - Asia/Pontianak',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3347',
          abbr: 'KST',
          gmt: '+09:00',
          name: 'Asia/Pyongyang',
          offset: -540,
          text: 'GMT+09:00 - Asia/Pyongyang',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3348',
          abbr: '+03',
          gmt: '+03:00',
          name: 'Asia/Qatar',
          offset: -180,
          text: 'GMT+03:00 - Asia/Qatar',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3349',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Asia/Qostanay',
          offset: -360,
          text: 'GMT+06:00 - Asia/Qostanay',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3350',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Qyzylorda',
          offset: -300,
          text: 'GMT+05:00 - Asia/Qyzylorda',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3351',
          abbr: '+0630',
          gmt: '+06:30',
          name: 'Asia/Rangoon',
          offset: -390,
          text: 'GMT+06:30 - Asia/Rangoon',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3352',
          abbr: '+03',
          gmt: '+03:00',
          name: 'Asia/Riyadh',
          offset: -180,
          text: 'GMT+03:00 - Asia/Riyadh',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3353',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Asia/Sakhalin',
          offset: -660,
          text: 'GMT+11:00 - Asia/Sakhalin',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3354',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Samarkand',
          offset: -300,
          text: 'GMT+05:00 - Asia/Samarkand',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3355',
          abbr: 'KST',
          gmt: '+09:00',
          name: 'Asia/Seoul',
          offset: -540,
          text: 'GMT+09:00 - Asia/Seoul',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3356',
          abbr: 'CST',
          gmt: '+08:00',
          name: 'Asia/Shanghai',
          offset: -480,
          text: 'GMT+08:00 - Asia/Shanghai',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3357',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Asia/Srednekolymsk',
          offset: -660,
          text: 'GMT+11:00 - Asia/Srednekolymsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3358',
          abbr: 'CST',
          gmt: '+08:00',
          name: 'Asia/Taipei',
          offset: -480,
          text: 'GMT+08:00 - Asia/Taipei',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3359',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Tashkent',
          offset: -300,
          text: 'GMT+05:00 - Asia/Tashkent',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3360',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Asia/Tbilisi',
          offset: -240,
          text: 'GMT+04:00 - Asia/Tbilisi',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3361',
          abbr: '+0330',
          gmt: '+03:30',
          name: 'Asia/Tehran',
          offset: -210,
          text: 'GMT+03:30 - Asia/Tehran',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3362',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Asia/Thimphu',
          offset: -360,
          text: 'GMT+06:00 - Asia/Thimphu',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3363',
          abbr: 'JST',
          gmt: '+09:00',
          name: 'Asia/Tokyo',
          offset: -540,
          text: 'GMT+09:00 - Asia/Tokyo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3364',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Asia/Tomsk',
          offset: -420,
          text: 'GMT+07:00 - Asia/Tomsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3365',
          abbr: '+08',
          gmt: '+08:00',
          name: 'Asia/Ulaanbaatar',
          offset: -480,
          text: 'GMT+08:00 - Asia/Ulaanbaatar',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3366',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Asia/Urumqi',
          offset: -360,
          text: 'GMT+06:00 - Asia/Urumqi',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3367',
          abbr: '+10',
          gmt: '+10:00',
          name: 'Asia/Ust-Nera',
          offset: -600,
          text: 'GMT+10:00 - Asia/Ust-Nera',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3368',
          abbr: '+10',
          gmt: '+10:00',
          name: 'Asia/Vladivostok',
          offset: -600,
          text: 'GMT+10:00 - Asia/Vladivostok',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3369',
          abbr: '+09',
          gmt: '+09:00',
          name: 'Asia/Yakutsk',
          offset: -540,
          text: 'GMT+09:00 - Asia/Yakutsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3370',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Asia/Yekaterinburg',
          offset: -300,
          text: 'GMT+05:00 - Asia/Yekaterinburg',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3371',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Asia/Yerevan',
          offset: -240,
          text: 'GMT+04:00 - Asia/Yerevan',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3372',
          abbr: '-01',
          gmt: '-01:00',
          name: 'Atlantic/Azores',
          offset: 60,
          text: 'GMT-01:00 - Atlantic/Azores',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3373',
          abbr: 'AST',
          gmt: '-04:00',
          name: 'Atlantic/Bermuda',
          offset: 240,
          text: 'GMT-04:00 - Atlantic/Bermuda',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3374',
          abbr: 'WET',
          gmt: '+00:00',
          name: 'Atlantic/Canary',
          offset: 0,
          text: 'GMT+00:00 - Atlantic/Canary',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3375',
          abbr: '-01',
          gmt: '-01:00',
          name: 'Atlantic/Cape_Verde',
          offset: 60,
          text: 'GMT-01:00 - Atlantic/Cape_Verde',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3376',
          abbr: 'WET',
          gmt: '+00:00',
          name: 'Atlantic/Faroe',
          offset: 0,
          text: 'GMT+00:00 - Atlantic/Faroe',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3377',
          abbr: 'WET',
          gmt: '+00:00',
          name: 'Atlantic/Madeira',
          offset: 0,
          text: 'GMT+00:00 - Atlantic/Madeira',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3378',
          abbr: 'GMT',
          gmt: '+00:00',
          name: 'Atlantic/Reykjavik',
          offset: 0,
          text: 'GMT+00:00 - Atlantic/Reykjavik',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3379',
          abbr: '-02',
          gmt: '-02:00',
          name: 'Atlantic/South_Georgia',
          offset: 120,
          text: 'GMT-02:00 - Atlantic/South_Georgia',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3380',
          abbr: '-03',
          gmt: '-03:00',
          name: 'Atlantic/Stanley',
          offset: 180,
          text: 'GMT-03:00 - Atlantic/Stanley',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3381',
          abbr: 'ACDT',
          gmt: '+10:30',
          name: 'Australia/Adelaide',
          offset: -630,
          text: 'GMT+10:30 - Australia/Adelaide',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3382',
          abbr: 'AEST',
          gmt: '+10:00',
          name: 'Australia/Brisbane',
          offset: -600,
          text: 'GMT+10:00 - Australia/Brisbane',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3383',
          abbr: 'ACDT',
          gmt: '+10:30',
          name: 'Australia/Broken_Hill',
          offset: -630,
          text: 'GMT+10:30 - Australia/Broken_Hill',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3384',
          abbr: 'ACST',
          gmt: '+09:30',
          name: 'Australia/Darwin',
          offset: -570,
          text: 'GMT+09:30 - Australia/Darwin',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3385',
          abbr: '+0845',
          gmt: '+08:45',
          name: 'Australia/Eucla',
          offset: -525,
          text: 'GMT+08:45 - Australia/Eucla',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3386',
          abbr: 'AEDT',
          gmt: '+11:00',
          name: 'Australia/Hobart',
          offset: -660,
          text: 'GMT+11:00 - Australia/Hobart',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3387',
          abbr: 'AEST',
          gmt: '+10:00',
          name: 'Australia/Lindeman',
          offset: -600,
          text: 'GMT+10:00 - Australia/Lindeman',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3388',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Australia/Lord_Howe',
          offset: -660,
          text: 'GMT+11:00 - Australia/Lord_Howe',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3389',
          abbr: 'AEDT',
          gmt: '+11:00',
          name: 'Australia/Melbourne',
          offset: -660,
          text: 'GMT+11:00 - Australia/Melbourne',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3390',
          abbr: 'AWST',
          gmt: '+08:00',
          name: 'Australia/Perth',
          offset: -480,
          text: 'GMT+08:00 - Australia/Perth',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3391',
          abbr: 'AEDT',
          gmt: '+11:00',
          name: 'Australia/Sydney',
          offset: -660,
          text: 'GMT+11:00 - Australia/Sydney',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3392',
          abbr: '-01',
          gmt: '-01:00',
          name: 'Etc/GMT+1',
          offset: 60,
          text: 'GMT-01:00 - Etc/GMT+1',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3393',
          abbr: '-10',
          gmt: '-10:00',
          name: 'Etc/GMT+10',
          offset: 600,
          text: 'GMT-10:00 - Etc/GMT+10',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3394',
          abbr: '-11',
          gmt: '-11:00',
          name: 'Etc/GMT+11',
          offset: 660,
          text: 'GMT-11:00 - Etc/GMT+11',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3395',
          abbr: '-12',
          gmt: '-12:00',
          name: 'Etc/GMT+12',
          offset: 720,
          text: 'GMT-12:00 - Etc/GMT+12',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3396',
          abbr: '-03',
          gmt: '-03:00',
          name: 'Etc/GMT+3',
          offset: 180,
          text: 'GMT-03:00 - Etc/GMT+3',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3397',
          abbr: '-04',
          gmt: '-04:00',
          name: 'Etc/GMT+4',
          offset: 240,
          text: 'GMT-04:00 - Etc/GMT+4',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3398',
          abbr: '-05',
          gmt: '-05:00',
          name: 'Etc/GMT+5',
          offset: 300,
          text: 'GMT-05:00 - Etc/GMT+5',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3399',
          abbr: '-06',
          gmt: '-06:00',
          name: 'Etc/GMT+6',
          offset: 360,
          text: 'GMT-06:00 - Etc/GMT+6',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3400',
          abbr: '-07',
          gmt: '-07:00',
          name: 'Etc/GMT+7',
          offset: 420,
          text: 'GMT-07:00 - Etc/GMT+7',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3401',
          abbr: '-08',
          gmt: '-08:00',
          name: 'Etc/GMT+8',
          offset: 480,
          text: 'GMT-08:00 - Etc/GMT+8',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3402',
          abbr: '-09',
          gmt: '-09:00',
          name: 'Etc/GMT+9',
          offset: 540,
          text: 'GMT-09:00 - Etc/GMT+9',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3403',
          abbr: 'GMT',
          gmt: '+00:00',
          name: 'Etc/GMT-0',
          offset: 0,
          text: 'GMT+00:00 - Etc/GMT-0',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3404',
          abbr: '+01',
          gmt: '+01:00',
          name: 'Etc/GMT-1',
          offset: -60,
          text: 'GMT+01:00 - Etc/GMT-1',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3405',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Etc/GMT-11',
          offset: -660,
          text: 'GMT+11:00 - Etc/GMT-11',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3406',
          abbr: '+13',
          gmt: '+13:00',
          name: 'Etc/GMT-13',
          offset: -780,
          text: 'GMT+13:00 - Etc/GMT-13',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3407',
          abbr: '+14',
          gmt: '+14:00',
          name: 'Etc/GMT-14',
          offset: -840,
          text: 'GMT+14:00 - Etc/GMT-14',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3408',
          abbr: '+02',
          gmt: '+02:00',
          name: 'Etc/GMT-2',
          offset: -120,
          text: 'GMT+02:00 - Etc/GMT-2',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3409',
          abbr: '+03',
          gmt: '+03:00',
          name: 'Etc/GMT-3',
          offset: -180,
          text: 'GMT+03:00 - Etc/GMT-3',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3410',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Etc/GMT-4',
          offset: -240,
          text: 'GMT+04:00 - Etc/GMT-4',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3411',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Etc/GMT-5',
          offset: -300,
          text: 'GMT+05:00 - Etc/GMT-5',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3412',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Etc/GMT-6',
          offset: -360,
          text: 'GMT+06:00 - Etc/GMT-6',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3413',
          abbr: '+08',
          gmt: '+08:00',
          name: 'Etc/GMT-8',
          offset: -480,
          text: 'GMT+08:00 - Etc/GMT-8',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3414',
          abbr: 'UTC',
          gmt: '+00:00',
          name: 'Etc/UTC',
          offset: 0,
          text: 'GMT+00:00 - Etc/UTC',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3415',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Amsterdam',
          offset: -60,
          text: 'GMT+01:00 - Europe/Amsterdam',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3416',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Andorra',
          offset: -60,
          text: 'GMT+01:00 - Europe/Andorra',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3417',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Europe/Astrakhan',
          offset: -240,
          text: 'GMT+04:00 - Europe/Astrakhan',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3418',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Athens',
          offset: -120,
          text: 'GMT+02:00 - Europe/Athens',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3419',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Belgrade',
          offset: -60,
          text: 'GMT+01:00 - Europe/Belgrade',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3420',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Berlin',
          offset: -60,
          text: 'GMT+01:00 - Europe/Berlin',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3421',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Brussels',
          offset: -60,
          text: 'GMT+01:00 - Europe/Brussels',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3422',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Bucharest',
          offset: -120,
          text: 'GMT+02:00 - Europe/Bucharest',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3423',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Budapest',
          offset: -60,
          text: 'GMT+01:00 - Europe/Budapest',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3424',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Chisinau',
          offset: -120,
          text: 'GMT+02:00 - Europe/Chisinau',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3425',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Copenhagen',
          offset: -60,
          text: 'GMT+01:00 - Europe/Copenhagen',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3426',
          abbr: 'GMT',
          gmt: '+00:00',
          name: 'Europe/Dublin',
          offset: 0,
          text: 'GMT+00:00 - Europe/Dublin',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3427',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Gibraltar',
          offset: -60,
          text: 'GMT+01:00 - Europe/Gibraltar',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3428',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Helsinki',
          offset: -120,
          text: 'GMT+02:00 - Europe/Helsinki',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3429',
          abbr: '+03',
          gmt: '+03:00',
          name: 'Europe/Istanbul',
          offset: -180,
          text: 'GMT+03:00 - Europe/Istanbul',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3430',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Kaliningrad',
          offset: -120,
          text: 'GMT+02:00 - Europe/Kaliningrad',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3431',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Kiev',
          offset: -120,
          text: 'GMT+02:00 - Europe/Kiev',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3432',
          abbr: '+03',
          gmt: '+03:00',
          name: 'Europe/Kirov',
          offset: -180,
          text: 'GMT+03:00 - Europe/Kirov',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3433',
          abbr: 'WET',
          gmt: '+00:00',
          name: 'Europe/Lisbon',
          offset: 0,
          text: 'GMT+00:00 - Europe/Lisbon',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3434',
          abbr: 'GMT',
          gmt: '+00:00',
          name: 'Europe/London',
          offset: 0,
          text: 'GMT+00:00 - Europe/London',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3435',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Luxembourg',
          offset: -60,
          text: 'GMT+01:00 - Europe/Luxembourg',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3436',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Madrid',
          offset: -60,
          text: 'GMT+01:00 - Europe/Madrid',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3437',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Malta',
          offset: -60,
          text: 'GMT+01:00 - Europe/Malta',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3438',
          abbr: '+03',
          gmt: '+03:00',
          name: 'Europe/Minsk',
          offset: -180,
          text: 'GMT+03:00 - Europe/Minsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3439',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Monaco',
          offset: -60,
          text: 'GMT+01:00 - Europe/Monaco',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3440',
          abbr: 'MSK',
          gmt: '+03:00',
          name: 'Europe/Moscow',
          offset: -180,
          text: 'GMT+03:00 - Europe/Moscow',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3441',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Oslo',
          offset: -60,
          text: 'GMT+01:00 - Europe/Oslo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3442',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Paris',
          offset: -60,
          text: 'GMT+01:00 - Europe/Paris',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3443',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Prague',
          offset: -60,
          text: 'GMT+01:00 - Europe/Prague',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3444',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Riga',
          offset: -120,
          text: 'GMT+02:00 - Europe/Riga',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3445',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Rome',
          offset: -60,
          text: 'GMT+01:00 - Europe/Rome',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3446',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Europe/Samara',
          offset: -240,
          text: 'GMT+04:00 - Europe/Samara',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3447',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Europe/Saratov',
          offset: -240,
          text: 'GMT+04:00 - Europe/Saratov',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3448',
          abbr: 'MSK',
          gmt: '+03:00',
          name: 'Europe/Simferopol',
          offset: -180,
          text: 'GMT+03:00 - Europe/Simferopol',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3449',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Sofia',
          offset: -120,
          text: 'GMT+02:00 - Europe/Sofia',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3450',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Stockholm',
          offset: -60,
          text: 'GMT+01:00 - Europe/Stockholm',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3451',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Tallinn',
          offset: -120,
          text: 'GMT+02:00 - Europe/Tallinn',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3452',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Tirane',
          offset: -60,
          text: 'GMT+01:00 - Europe/Tirane',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3453',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Europe/Ulyanovsk',
          offset: -240,
          text: 'GMT+04:00 - Europe/Ulyanovsk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3454',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Uzhgorod',
          offset: -120,
          text: 'GMT+02:00 - Europe/Uzhgorod',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3455',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Vienna',
          offset: -60,
          text: 'GMT+01:00 - Europe/Vienna',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3456',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Vilnius',
          offset: -120,
          text: 'GMT+02:00 - Europe/Vilnius',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3457',
          abbr: '+03',
          gmt: '+03:00',
          name: 'Europe/Volgograd',
          offset: -180,
          text: 'GMT+03:00 - Europe/Volgograd',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3458',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Warsaw',
          offset: -60,
          text: 'GMT+01:00 - Europe/Warsaw',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3459',
          abbr: 'EET',
          gmt: '+02:00',
          name: 'Europe/Zaporozhye',
          offset: -120,
          text: 'GMT+02:00 - Europe/Zaporozhye',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3460',
          abbr: 'CET',
          gmt: '+01:00',
          name: 'Europe/Zurich',
          offset: -60,
          text: 'GMT+01:00 - Europe/Zurich',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3461',
          abbr: '+06',
          gmt: '+06:00',
          name: 'Indian/Chagos',
          offset: -360,
          text: 'GMT+06:00 - Indian/Chagos',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3462',
          abbr: '+07',
          gmt: '+07:00',
          name: 'Indian/Christmas',
          offset: -420,
          text: 'GMT+07:00 - Indian/Christmas',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3463',
          abbr: '+0630',
          gmt: '+06:30',
          name: 'Indian/Cocos',
          offset: -390,
          text: 'GMT+06:30 - Indian/Cocos',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3464',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Indian/Kerguelen',
          offset: -300,
          text: 'GMT+05:00 - Indian/Kerguelen',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3465',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Indian/Mahe',
          offset: -240,
          text: 'GMT+04:00 - Indian/Mahe',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3466',
          abbr: '+05',
          gmt: '+05:00',
          name: 'Indian/Maldives',
          offset: -300,
          text: 'GMT+05:00 - Indian/Maldives',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3467',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Indian/Mauritius',
          offset: -240,
          text: 'GMT+04:00 - Indian/Mauritius',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3468',
          abbr: '+04',
          gmt: '+04:00',
          name: 'Indian/Reunion',
          offset: -240,
          text: 'GMT+04:00 - Indian/Reunion',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3469',
          abbr: '+13',
          gmt: '+13:00',
          name: 'Pacific/Apia',
          offset: -780,
          text: 'GMT+13:00 - Pacific/Apia',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3470',
          abbr: 'NZDT',
          gmt: '+13:00',
          name: 'Pacific/Auckland',
          offset: -780,
          text: 'GMT+13:00 - Pacific/Auckland',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3471',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Pacific/Bougainville',
          offset: -660,
          text: 'GMT+11:00 - Pacific/Bougainville',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3472',
          abbr: '+1345',
          gmt: '+13:45',
          name: 'Pacific/Chatham',
          offset: -825,
          text: 'GMT+13:45 - Pacific/Chatham',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3473',
          abbr: '+10',
          gmt: '+10:00',
          name: 'Pacific/Chuuk',
          offset: -600,
          text: 'GMT+10:00 - Pacific/Chuuk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3474',
          abbr: '-05',
          gmt: '-05:00',
          name: 'Pacific/Easter',
          offset: 300,
          text: 'GMT-05:00 - Pacific/Easter',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3475',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Pacific/Efate',
          offset: -660,
          text: 'GMT+11:00 - Pacific/Efate',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3476',
          abbr: '+13',
          gmt: '+13:00',
          name: 'Pacific/Enderbury',
          offset: -780,
          text: 'GMT+13:00 - Pacific/Enderbury',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3477',
          abbr: '+13',
          gmt: '+13:00',
          name: 'Pacific/Fakaofo',
          offset: -780,
          text: 'GMT+13:00 - Pacific/Fakaofo',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3478',
          abbr: '+13',
          gmt: '+13:00',
          name: 'Pacific/Fiji',
          offset: -780,
          text: 'GMT+13:00 - Pacific/Fiji',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3479',
          abbr: '-06',
          gmt: '-06:00',
          name: 'Pacific/Galapagos',
          offset: 360,
          text: 'GMT-06:00 - Pacific/Galapagos',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3480',
          abbr: '-09',
          gmt: '-09:00',
          name: 'Pacific/Gambier',
          offset: 540,
          text: 'GMT-09:00 - Pacific/Gambier',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3481',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Pacific/Guadalcanal',
          offset: -660,
          text: 'GMT+11:00 - Pacific/Guadalcanal',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3482',
          abbr: 'ChST',
          gmt: '+10:00',
          name: 'Pacific/Guam',
          offset: -600,
          text: 'GMT+10:00 - Pacific/Guam',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3483',
          abbr: 'HST',
          gmt: '-10:00',
          name: 'Pacific/Honolulu',
          offset: 600,
          text: 'GMT-10:00 - Pacific/Honolulu',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3484',
          abbr: '+14',
          gmt: '+14:00',
          name: 'Pacific/Kiritimati',
          offset: -840,
          text: 'GMT+14:00 - Pacific/Kiritimati',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3485',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Pacific/Kosrae',
          offset: -660,
          text: 'GMT+11:00 - Pacific/Kosrae',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3486',
          abbr: '+12',
          gmt: '+12:00',
          name: 'Pacific/Kwajalein',
          offset: -720,
          text: 'GMT+12:00 - Pacific/Kwajalein',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3487',
          abbr: '+12',
          gmt: '+12:00',
          name: 'Pacific/Majuro',
          offset: -720,
          text: 'GMT+12:00 - Pacific/Majuro',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3488',
          abbr: '-0930',
          gmt: '-09:30',
          name: 'Pacific/Marquesas',
          offset: 570,
          text: 'GMT-09:30 - Pacific/Marquesas',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3489',
          abbr: '+12',
          gmt: '+12:00',
          name: 'Pacific/Nauru',
          offset: -720,
          text: 'GMT+12:00 - Pacific/Nauru',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3490',
          abbr: '-11',
          gmt: '-11:00',
          name: 'Pacific/Niue',
          offset: 660,
          text: 'GMT-11:00 - Pacific/Niue',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3491',
          abbr: '+12',
          gmt: '+12:00',
          name: 'Pacific/Norfolk',
          offset: -720,
          text: 'GMT+12:00 - Pacific/Norfolk',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3492',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Pacific/Noumea',
          offset: -660,
          text: 'GMT+11:00 - Pacific/Noumea',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3493',
          abbr: 'SST',
          gmt: '-11:00',
          name: 'Pacific/Pago_Pago',
          offset: 660,
          text: 'GMT-11:00 - Pacific/Pago_Pago',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3494',
          abbr: '+09',
          gmt: '+09:00',
          name: 'Pacific/Palau',
          offset: -540,
          text: 'GMT+09:00 - Pacific/Palau',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3495',
          abbr: '-08',
          gmt: '-08:00',
          name: 'Pacific/Pitcairn',
          offset: 480,
          text: 'GMT-08:00 - Pacific/Pitcairn',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3496',
          abbr: '+11',
          gmt: '+11:00',
          name: 'Pacific/Pohnpei',
          offset: -660,
          text: 'GMT+11:00 - Pacific/Pohnpei',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3497',
          abbr: '+10',
          gmt: '+10:00',
          name: 'Pacific/Port_Moresby',
          offset: -600,
          text: 'GMT+10:00 - Pacific/Port_Moresby',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3498',
          abbr: '-10',
          gmt: '-10:00',
          name: 'Pacific/Rarotonga',
          offset: 600,
          text: 'GMT-10:00 - Pacific/Rarotonga',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3499',
          abbr: '-10',
          gmt: '-10:00',
          name: 'Pacific/Tahiti',
          offset: 600,
          text: 'GMT-10:00 - Pacific/Tahiti',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3500',
          abbr: '+12',
          gmt: '+12:00',
          name: 'Pacific/Tarawa',
          offset: -720,
          text: 'GMT+12:00 - Pacific/Tarawa',
          type: 'Timezones',
        },
        {
          $$hashKey: 'object:3501',
          abbr: '+13',
          gmt: '+13:00',
          name: 'Pacific/Tongatapu',
          offset: -780,
          text: 'GMT+13:00 - Pacific/Tongatapu',
          type: 'Timezones',
        },
      ],
    },
  }),
}
</script>

<style>
html,
body {
  margin: 0;
  height: 100%;
  font-family: -apple-system, sans-serif;
}

#app {
  height: 100%;
  max-width: 20rem;
  margin: 10rem auto 0;
}

hr {
  border: none;
  border-bottom: 1px solid #cacaca;
  margin-bottom: 1em;
  padding-top: 1em;
  width: 90%;
}

.divider {
  height: 1px;
  margin: 9px 0;
  overflow: hidden;
  background-color: #e5e5e5;
}
</style>
