name: "Install Dependencies"
description: "Install cached dependencies"

runs:
  using: "composite"
  steps:

    - uses: actions/cache@v4
      shell: bash
      id: pnpm-cache
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
        restore-keys: |
          ${{ runner.os }}-pnpm-

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
